### ISSUE TITLE
Why is it necessary to drop params that aren't used in the filter?

### ISSUE THREAD

**Issue by abitdodgy** [rcdilorenzo/filtrex#33]
For example:

```elixir
def index(conn, params)
  filter_params = Map.drop(params, ~w(account_id))
  # ...
end
```

Why not ignore keys not presence in `Model.filter_options` by default? That way it doesn't raise an error when unknown key-value pairs are used.

**Comment by rcdilorenzo** [comment]
This is for security reasons. For example, consider that you are adding to the params to specify a particular `user_id` to filter transactions. If you forget to add this to the allowed filter params with the appropriate constraint, all of the transactions will appear. Additionally, it follows the pattern of alerting the developer to a problem sooner rather than later through a more subtle problem such as in this simple example.

Does that make sense?

**Comment by abitdodgy** [comment]
That makes sense. Thanks for the explanation.
