### ISSUE TITLE
Add support for 'or' queries

### ISSUE THREAD

**Issue by Mbuckley0** [rcdilorenzo/filtrex#35]
It would be useful if you could filter on multiple columns with an or query
i.e. 'name_or_email_contains' which would find all of the users whose name or email contains the passed in string.

**Comment by rcdilorenzo** [comment]
Hmm... how do you envision separating this fro a field named `name_or_email`? Were you thinking a specific configuration to allow combining only certain fields?

**Comment by Mbuckley0** [comment]
I think having a specific configuration to allow for the oring of fields would be the best way to go.

**Comment by rcdilorenzo** [comment]
You mean perhaps something like this? Or is there perhaps a better design we can conjure up?

```elixir
config = [
  %Filtrex.Type.Config{type: :text, keys: ~w(name email)},
  %Filtrex.Type.Config{type: :combination_or, keys: ~w(name email)}
]
```

**Comment by Mbuckley0** [comment]
That should work well. I can't think of any better design which will work at the moment.

**Comment by rcdilorenzo** [comment]
Feel free to open a pull-request. I'm a bit busy at the moment but still want to think a bit longer to see if we can not have "magic" atoms but somehow use modules or types to solve this configuration problem.

**Comment by rcdilorenzo** [comment]
After giving it some thought, I think we might want to do something like #36 and then implement something with that syntax to define an OR query.

**Comment by rcdilorenzo** [comment]
As I think about this issue more and more, the less I feel that column based `or`-ing should be a responsibility of this library. It could easily be added as an additional filter on an Ecto query with a separate config or could be parsed in the controller.

One of the primary issues with implementing something like this is the configuration needs to know what keys can be passed in. In this case, however, the functionality could not be directly added as a configuration type since it would have to match keys quite differently. I'm open to anyone taking a stab at it if you think it is an essential feature, but for now I will close the issue.
