### ISSUE TITLE
Add support for nil on datetime fields

### ISSUE THREAD

**Issue by programisti** [rcdilorenzo/filtrex#62]
When trying to filter `inserted_at=nil` it returns Timex error ```Expected 4 digit year, but got `n` instead.```
example url: `/posts?_utf8=✓&post%5Binserted_at%5D=nil`

Steps to reproduce:

```elixir
Filtrex.parse_params([ %Filtrex.Type.Config{keys: ["inserted_at"], options: %{}, type: :datetime} ], %{"inserted_at" => "nil"}
```

will return
```elixir
{:error, "Expected 4 digit year, but got `n` instead."}
```

**Comment by rcdilorenzo** [comment]
The issue here is that HTML parameters don't usually work with a language-specific construct of `nil`. For example, if we were writing JavaScript, it might be `null`. If it was C, we might use `NULL`. If it was Python, we might use `None`.

Fundamentally, the point you bring up is still an extremely valuable one, but would need to be support as a matcher suffix such as `_is_null` (e.g. `inserted_at_is_null`). Feel free to open a pull request if you are so inclined to add these to the various [filter types](https://github.com/rcdilorenzo/filtrex#filter-types). Thanks for adding this. 👍

**Comment by rcdilorenzo** [comment]
Closed as stale.
